### ISSUE TITLE
Config is missing?

### ISSUE THREAD

**Issue by guyisra** [tilezen/tapalcatl#46]
this, as opposed to tapalcatl-py doesn't seem to have documentation on how to provide configurations

I see from the code that that I can provide a config file, but what should its structure be?

**Comment by zerebubuth** [comment]
Yup, sorry about that. A quick place to get started is:

```
listen :8000
handler {"mime":{"json":"application/json","mvt":"application/x-protobuf","mvtb":"application/x-protobuf","topojson":"application/json"},"storage":{"tmp":{"type":"file","basedir":"/tmp","metatilesize":1,"layer":"all"}},"pattern":{"/{z:[0-9]+}/{x:[0-9]+}/{y:[0-9]+}.{fmt}":{"storage":"tmp"}}}
```

(based on [the defaults for the chef-tapalcatl recipe](https://github.com/tilezen/chef-tapalcatl/blob/30c025c11a06967a6820252f8c9512472e4ac2ef/attributes/default.rb#L33))

The main part of the config is the `handler` section, which takes a single line (yuck, I know, sorry) of JSON, which is easier to read as:

```js
{
  "mime": {
    "json": "application/json",
    "mvt": "application/x-protobuf",
    "mvtb": "application/x-protobuf",
    "topojson": "application/json"
  },
  "storage": {
    "tmp": {
      "type": "file",
      "basedir": "/tmp",
      "metatilesize": 1,
      "layer": "all"
    }
  },
  "pattern": {
    "/{z:[0-9]+}/{x:[0-9]+}/{y:[0-9]+}.{fmt}": {
      "storage": "tmp"
    }
  }
}
```

Which is a good config to start from when doing local development work, serving tiles from local disk. Note that the `storage` section defines a set of names - in this case just `tmp`, which the `pattern` section references. For tiles on S3, we'd use something like:

```js
{
  "mime": {
    "json": "application/json",
    "topojson": "application/json",
    "mvt": "application/x-protobuf",
    "mvtb": "application/x-protobuf"
  },
  "aws": {
    "region": "us-east-1"
  },
  "storage": {
    "s3dev": {
      "type": "s3",
      "bucket": "your-bucket-here",
      "layer": "all",
      "metatilesize": 2,
      "keypattern": "/{prefix}/{hash}/{layer}/{z}/{x}/{y}.{fmt}",
      "healthcheck": "/healthcheck.txt"
    }
  },
  "pattern": {
    "/tilezen/vector/v1/all/{z:[0-9]+}/{x:[0-9]+}/{y:[0-9]+}.{fmt}": {
      "storage": "s3dev",
      "Prefix": "20180619"
    }
  }
}
```

There's a few things going on here:

* The `healthcheck` should be a static file on S3 that tapalcatl will fetch to check that it has access to S3. Since S3 is (usually) very stable, this is generally more of a permissions check and node health check. This can be exposed via the `healthcheck` top level config item or command line option so that an ELB or similar can monitor it.
* The `keypattern` is what we use; a date prefix concatenated with a distributive hash, then the tile coordinates. If you're generating tiles using `tileops` then you shouldn't need to alter this.
* Multiple `pattern`s are supported. At Mapzen, we had support for multiple versions on different prefixes, but you might not need this.

Hope that helps!
